import * as Notifications from 'expo-notifications';
import { SchedulableTriggerInputTypes } from 'expo-notifications';

Notifications.setNotificationHandler({
    handleNotification: async () => ({
      shouldShowAlert: true,
      shouldPlaySound: true,
      shouldSetBadge: false,
      shouldShowBanner: true, 
      shouldShowList: true,
    }),
  });

export async function requestNotificationPermissions () {
        // 1. Check existing permission status without prompting
    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;

  // 2. If not granted yet, ask the user with a system prompt
    if (existingStatus !== 'granted') {
        const { status } = await Notifications.requestPermissionsAsync();
        finalStatus = status;
    }

    // 3. Handle the final status
    if (finalStatus !== 'granted') {
        alert('Failed to get push token for push notifications!');
        return false;
    }
    
    return true;

}

export async function scheduleExpiryReminder(itemName: string, expiryDate: Date) {
    // 1. Copy the expiration date picked by the user
    const reminderDate = new Date(expiryDate);
    
    // 2. Subtract exactly 7 days from it
    reminderDate.setDate(reminderDate.getDate() - 7);

    // 3. Ensure the warning moment is in the future before scheduling
    if (reminderDate > new Date()) {
        try {
            // 2. Capture the string ID generated by Expo
            const notificationId = await Notifications.scheduleNotificationAsync({
                content: {
                    title: "⚠️ Expiry Warning!",
                    body: `Your ${itemName} is expiring in 1 week!`,
                    sound: true,
                },
                trigger: {
                    type: SchedulableTriggerInputTypes.DATE,
                    date: reminderDate,
                },
            });
            
            console.log(`🎯 Alarm Set: Reminder scheduled with ID: ${notificationId}`);
            return notificationId; // 3. Return it to the caller!
            
        } catch (error) {
            console.error("Failed to schedule production notification:", error);
            return undefined;
        }
    }
    return undefined;
}